name: Test WorkFlow

on: 
  workflow_dispatch:

concurrency:
  group: "test group"
  cancel-in-progress: true

jobs: 
  testjava:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: setup java
      uses: actions/setup-java@v1
      with: 
        java-version: '17'
    - name: run jar file
      run: java -jar 'environment/java/swagger-test-1.0.0.jar'

