name: Test WorkFlow

on: 
  push:
    branches:
      - main
    paths:
      - swagger-test/src/main/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "test group"
  cancel-in-progress: true

jobs: 
  testjava:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}swagger-ui
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
      with: 
        path: main
    - name: setup java
      uses: actions/setup-java@v1
      with: 
        java-version: '17'
    - name: run jar file
      run: java -jar 'environment/java/swagger-test-1.0.0.jar'
    - name: get json file
      run: wget -P /main/docs/dist/swagger-ui http://localhost:8765/v3/api-docs
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'main/docs/dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
